version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=landing_page_project
      - DB_USERNAME=root
      - DB_PASSWORD=Strongp@ssword123
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravel_network
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_DATABASE: landing_page_project
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: Strongp@ssword123
    ports:
      - "3306:3306"
    networks:
      - laravel_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
